version: '2'
services:
  deploy:
    environment:
      - FIREBASE_PROJECT
      - FIREBASE_TOKEN
      - FIREBASE_CONF_JS
    build:
      context: ./
      dockerfile: deploy.dockerfile
    volumes:
      - ./:/app
