version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
         name: hoge
         command: |
           ls -lar
      - run:
         name: createconf
         command: |
           echo ${FIREBASE_CONF_JS} > ${HOME}/${CIRCLE_PROJECT_REPONAME}/public/firebase-conf.js
      - run:
          name: deploy
          command: |
            docker-compose -f deploy-develop-compose.yml up --build
