version: 2
jobs:
  build:
    docker:
      - image: .circleci/docker-firebase:latest
    working_directory: ~/project
    steps:
      - checkout
      - deploy:
          branch: master
      commands: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
